"""VIGOR core package."""

from vigor_core.agent_config import (
    AdapterSpec,
    AgentConfig,
    BackendSpec,
    FactoryRef,
    MCPServerSpec,
    RoutingPolicy,
)
from vigor_core.archive import RunArchive
from vigor_core.audit import (
    AuditEvent,
    AuditOutcome,
    AuditSink,
    InMemoryAuditSink,
    NullAuditSink,
)
from vigor_core.errors import (
    AdapterContractError,
    ArchiveLockedError,
    BudgetExceededError,
    CompileError,
    ExportError,
    ReviewerError,
    SchemaValidationError,
    ToolTimeoutError,
    VigorError,
)
from vigor_core.interfaces import (
    AgentBackend,
    DomainAdapter,
    GenerationRequest,
    GenerationResult,
    PatchProposal,
    PatchProposalRequest,
    RepresentationPlan,
    ReviewRequest,
    ReviewResult,
    RunContext,
    ToolBackend,
    ToolResult,
    ValidationReport,
)
from vigor_core.plugin import (
    OpenPluginManifest,
    SkillTemplate,
    export_plugin_json,
    export_skill_md,
)
from vigor_core.registry import (
    export_json_schema,
    get_ir_model,
    register_ir,
    registered_ir_versions,
    validate_ir_body,
)
from vigor_core.schemas import (
    ID_PATTERN,
    AdapterManifest,
    AdjudicationReport,
    ArtifactIR,
    Budgets,
    CompileResult,
    Constraint,
    Decision,
    ExportBundle,
    ExportEntry,
    Finding,
    Frontier,
    FrontierCandidate,
    ObservableArtifact,
    PatchPlan,
    ProvenanceActivity,
    ProvenanceRecord,
    ReferenceArtifact,
    ReviewReport,
    StopReason,
    TaskSpec,
    ToolManifest,
    Usage,
)
from vigor_core.schemas import (
    RuntimeErrorRecord as VigorRuntimeError,
)
from vigor_core.scoring import (
    AdjudicationInputs,
    ScoringPolicy,
    adjudicate,
    build_frontier,
    normalize_score,
    select_best,
)
from vigor_core.util import (
    safe_relative,
    sha256_bytes,
    sha256_file,
    sha256_text,
    stable_json,
    utcnow_iso,
)

__all__ = [
    "ID_PATTERN",
    "AdapterContractError",
    "AdapterManifest",
    "AdapterSpec",
    "AdjudicationInputs",
    "AdjudicationReport",
    "AgentBackend",
    "AgentConfig",
    "ArchiveLockedError",
    "ArtifactIR",
    "AuditEvent",
    "AuditOutcome",
    "AuditSink",
    "BackendSpec",
    "BudgetExceededError",
    "Budgets",
    "CompileError",
    "CompileResult",
    "Constraint",
    "Decision",
    "DomainAdapter",
    "ExportBundle",
    "ExportEntry",
    "ExportError",
    "FactoryRef",
    "Finding",
    "Frontier",
    "FrontierCandidate",
    "GenerationRequest",
    "GenerationResult",
    "InMemoryAuditSink",
    "MCPServerSpec",
    "NullAuditSink",
    "ObservableArtifact",
    "OpenPluginManifest",
    "PatchPlan",
    "PatchProposal",
    "PatchProposalRequest",
    "ProvenanceActivity",
    "ProvenanceRecord",
    "ReferenceArtifact",
    "RepresentationPlan",
    "ReviewReport",
    "ReviewRequest",
    "ReviewResult",
    "ReviewerError",
    "RoutingPolicy",
    "RunArchive",
    "RunContext",
    "SchemaValidationError",
    "ScoringPolicy",
    "SkillTemplate",
    "StopReason",
    "TaskSpec",
    "ToolBackend",
    "ToolManifest",
    "ToolResult",
    "ToolTimeoutError",
    "Usage",
    "ValidationReport",
    "VigorError",
    "VigorRuntimeError",
    "adjudicate",
    "build_frontier",
    "export_json_schema",
    "export_plugin_json",
    "export_skill_md",
    "get_ir_model",
    "normalize_score",
    "register_ir",
    "registered_ir_versions",
    "safe_relative",
    "select_best",
    "sha256_bytes",
    "sha256_file",
    "sha256_text",
    "stable_json",
    "utcnow_iso",
    "validate_ir_body",
]

__version__ = "0.1.0"
