"""OpenSCAD text generation for first-slice CAD IR."""

from __future__ import annotations

from vigor_adapter_cad.ir import CadParametricIRV1


def _num(value: float) -> str:
    return f"{value:.4f}".rstrip("0").rstrip(".")


def _hole_count(ir: CadParametricIRV1) -> int:
    for feature in ir.features:
        if feature.type == "mounting_holes":
            return 4 if feature.count is None else feature.count
    return 0


def render_openscad(ir: CadParametricIRV1) -> str:
    p = ir.parameters
    hole_count = _hole_count(ir)
    holes = _hole_translates(ir, hole_count)
    ribs = _rib_translates(ir) if p.rib_count > 0 else []
    base_cube = (
        f"  cube([{_num(p.width_mm)}, {_num(p.height_mm)}, "
        f"{_num(p.thickness_mm)}], center = false);"
    )
    return "\n".join(
        [
            "// Generated by VIGOR CAD adapter. Units: mm.",
            "$fn = 48;",
            "",
            "difference() {",
            base_cube,
            *holes,
            "}",
            "",
            "union() {",
            *ribs,
            "}",
            "",
        ]
    )


def _hole_translates(ir: CadParametricIRV1, count: int) -> list[str]:
    if count <= 0:
        return []
    p = ir.parameters
    z = -0.5
    h = p.thickness_mm + 1.0
    positions = [
        (p.hole_margin_mm, p.hole_margin_mm),
        (p.width_mm - p.hole_margin_mm, p.hole_margin_mm),
        (p.hole_margin_mm, p.height_mm - p.hole_margin_mm),
        (p.width_mm - p.hole_margin_mm, p.height_mm - p.hole_margin_mm),
    ][:count]
    return [
        "  translate(["
        f"{_num(x)}, {_num(y)}, {_num(z)}]) "
        f"cylinder(h = {_num(h)}, d = {_num(p.hole_diameter_mm)});"
        for x, y in positions
    ]


def _rib_translates(ir: CadParametricIRV1) -> list[str]:
    p = ir.parameters
    if p.rib_count <= 0:
        return []
    spacing = p.width_mm / (p.rib_count + 1)
    ribs = []
    for idx in range(p.rib_count):
        x = spacing * (idx + 1) - p.rib_thickness_mm / 2.0
        rib_cube = (
            f"cube([{_num(p.rib_thickness_mm)}, {_num(p.height_mm)}, "
            f"{_num(p.thickness_mm)}], center = false);"
        )
        ribs.append(f"  translate([{_num(x)}, 0, {_num(p.thickness_mm)}]) {rib_cube}")
    return ribs
